export const TableDetails = [
  {
    name: 'Samson',
    date: '2024-12-10',
    email: 'Olamide@gmail.com',
    type: 'Income',
    amount: '3000',
    status: 'Pending',
  },
  {
    name: 'Ola',
    date: '2024-12-11',
    email: 'Ola@gmail.com',
    type: 'Income',
    amount: '4000',
    status: 'Success',
  },
  {
    name: 'Yemi',
    date: '2024-12-11',
    email: 'Ola@gmail.com',
    type: 'Income',
    amount: '4000',
    status: 'Failed',
  },
  {
    name: 'Tobi',
    date: '2024-12-10',
    email: 'tobe@gmail.com',
    type: 'Income',
    amount: '3000',
    status: 'Pending',
  },
  {
    name: 'Jeremy',
    date: '2024-12-11',
    email: 'jeremy@gmail.com',
    type: 'Outgoing',
    amount: '1000',
    status: 'Failed',
  },
  {
    name: 'Anthonyemi',
    date: '2024-12-11',
    email: 'anthony@gmail.com',
    type: 'Expense',
    amount: '1000',
    status: 'Failed',
  },
  {
    name: 'Olaye',
    date: '2024-12-11',
    email: 'olaye@gmail.com',
    type: 'Expense',
    amount: '1000',
    status: 'Pending',
  },
  {
    name: 'Daniel',
    date: '2022-12-10',
    email: 'Olamide@gmail.com',
    type: 'Income',
    amount: '3000',
    status: 'Pending',
  },
  {
    name: 'Cynthia',
    date: '2023-10-11',
    email: 'Ola@gmail.com',
    type: 'Income',
    amount: '4000',
    status: 'Success',
  },
  {
    name: 'Wole',
    date: '2021-11-11',
    email: 'Ola@gmail.com',
    type: 'Outgoing',
    amount: '4000',
    status: 'Success',
  },
  {
    name: 'John',
    date: '2022-12-10',
    email: 'Olamide@gmail.com',
    type: 'Income',
    amount: '3000',
    status: 'Failed',
  },
  {
    name: 'Cynthia',
    date: '2023-03-11',
    email: 'Ola@gmail.com',
    type: 'Income',
    amount: '7000',
    status: 'Success',
  },
  {
    name: 'James',
    date: '2021-03-11',
    email: 'Ola@gmail.com',
    type: 'Outgoing',
    amount: '2000',
    status: 'Pending',
  },
];

export const transactionBalance = [
  {
    name: 'Balances',
    amount: '10,000',
  },
  {
    name: 'Savings',
    amount: '7,000',
  },
  {
    name: 'Incomes',
    amount: '24,000',
  },
  {
    name: 'Expenses',
    amount: '18,000',
  },
];
