export const TableDetails = [
  {
    name: 'Samson',
    date: '2024-12-10',
    email: 'Olamide@gmail.com',
    type: 'Income',
    amount: '3000',
    status: 'Pending',
  },
  {
    name: 'Ola',
    date: '2024-12-11',
    email: 'Ola@gmail.com',
    type: 'Income',
    amount: '4000',
    status: 'Success',
  },
  {
    name: 'Yemi',
    date: '2024-12-11',
    email: 'Ola@gmail.com',
    type: 'Income',
    amount: '4000',
    status: 'Failed',
  },
  {
    name: 'Tobi',
    date: '2024-12-10',
    email: 'tobe@gmail.com',
    type: 'Income',
    amount: '3000',
    status: 'Pending',
  },
  {
    name: 'Jeremy',
    date: '2024-12-11',
    email: 'jeremy@gmail.com',
    type: 'Income',
    amount: '9000',
    status: 'Success',
  },
  {
    name: 'Anthonyemi',
    date: '2024-12-11',
    email: 'anthony@gmail.com',
    type: 'Expense',
    amount: '1000',
    status: 'Failed',
  },
  {
    name: 'Olaye',
    date: '2024-12-11',
    email: 'olaye@gmail.com',
    type: 'Expense',
    amount: '1000',
    status: 'Pending',
  },
];
